version: "3.9"
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    env_file: .env
    environment:
      DB_HOST: db
    depends_on:
      - db
    ports:
      - "8000:8000"
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    environment:
      - VITE_API_URL=${VITE_API_URL}
    depends_on:
      - backend
    ports:
      - "5173:80"
volumes:
  dbdata: